

service: service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  environment:
    KMS_ALIAS_ARN: ${file(./env-variables.yml):kmsAliasArn}
    PCI_BUCKET: ${file(./env-variables.yml):pciBucket}
    ENCRYPTION_CONTEXT_USER_NAME: ${file(./env-variables.yml):encryptionContextUserName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - kms:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"  

functions:
  tokenizer:
    handler: handler.handle
    events:
      - http: 'POST /'