

service: service

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - kms:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:*
      Resource: "*"  

functions:
  tokenizer:
    handler: handler.handle
    events:
      - http: 'POST /'